# Jekyll
gems:
  - jekyll-redirect-from

# Custom
siteTitle: Williamgrimes
siteDescription: A personal webpage for William Grimes.
avatar: img/profile2.jpg
background: img/background4.jpg
description: Hi. I'm William Grimes. Thanks for visiting my personal site!
resumeFile: /cv/william_grimes_cv.pdf

icons:
  - icon: page-pdf
    link: resume.html
    title: Resume
  - icon: social-github
    link: https://github.com/williamgrimes
    title: Github
  - icon: social-linkedin
    link: https://www.linkedin.com/in/william-grimes
    title: LinkedIn
  - icon: mail
    link: mailto:williamgrimes@gmx.com
    title: email

projects:
  - name: Project WEF Oceans
    link: https://dssg.uchicago.edu/project/fishingriskframework/
  - name: London Fire Brigade
    link: http://blog.asidatascience.com/how-to-put-out-a-fire-using-old-reports/
