# Jekyll
gems:
  - jekyll-redirect-from

# Custom
siteTitle: Corgi
siteDescription: My awesome personal site, i'm a Corgi!
avatar: img/avatar.jpg
background: img/background.jpg
description: Hey I'm William Grimes. Thanks for visiting my personal site!
resumeFile: https://www.dropbox.com/s/dt2ri8xbcuqro90/william_grimes_cover_letter.pdf?dl=0

icons:
  - icon: page-pdf
    link: resume.html
    title: Curriculum Vitae
  - icon: social-github
    link: https://github.com/williamgrimes
    title: Github
  - icon: social-linkedin
    link: https://www.linkedin.com/in/william-grimes
    title: LinkedIn
  - icon: mail
    link: https://www.reddit.com/r/corgi
    title: Reddit

projects:
  - name: Jekyll Configurable Site
    link: https://github.com/DDuarte/JekyllConfigurablePersonalSite
  - name: JSON Configurable Site
    link: https://github.com/christophior/JSONConfigurablePersonalSite
